SELECT
  security_metrics.time_bucket,
  security_metrics.total_attempts,
  security_metrics.suspicious_attempts,
  security_metrics.unique_ips,
  security_metrics.unique_referrers,
  security_metrics.high_attempt_count,
  security_metrics.max_attempts
FROM
  security_metrics;