services:
  website:
    build:
      context: ./packages/website
      dockerfile: Dockerfile
    image: astrotribe-website:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
