services:
  strapi:
    build:
      context: ./
      dockerfile: apps/cms/Dockerfile.develop
    container_name: astrotribe-strapi
    volumes:
      - ./apps/cms:/app/apps/cms
      - /app/apps/cms/node_modules
      - /app/apps/cms/.cache
      - /app/apps/cms/build
    ports:
      - '1337:1337'
    depends_on:
      - strapi-db
    environment:
      - NODE_ENV=development
      - SEED_DATA=true
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=hzD2uEmNx0oeTio1nkAliA==,2nsFZFEZqwlednX6Z+n8hQ==,uHBO8R2S8TgT+4/5U3D0Ew==,eJg+9WdVPM1wigrr1QAs9A==
      - API_TOKEN_SALT=p/A0ZPOuZwizyOfg15aPxw==
      - ADMIN_JWT_SECRET=ktIm9hdA8hldeD+XVARBDw==
      - JWT_SECRET=/wY80OqWQiVKagSd7uQkvg==
      # DATABASE
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
      # SUPABASE
      - SUPABASE_PROJECT_URL=http://127.0.0.1:54321
      - SUPABASE_BUCKET=articles
      - SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - SUPABASE_STORAGE_URL=http://127.0.0.1:54321/storage/v1/s3
      - SUPABASE_DIRECTORY=blog
    networks:
      - astrotribe-strapi-network

  strapi-db:
    image: postgres:14
    container_name: astrotribe-strapi-db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - astrotribe-strapi-network

volumes:
  strapi-pgdata:

networks:
  astrotribe-strapi-network:
    name: astrotribe-strapi-network
    driver: bridge
