export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      strapi: {
        url: '',
      },
      formbricksEnvironment: '',
      formbricksHost: '',
      supabaseUrl: '',
      supabaseKey: '',
      aeAuthUrl: '',
      aeLoginUrl: '',
      aeAppUrl: '',
      aeAdminUrl: '',
      aeMonitoringUrl: '',
      aeWebsiteUrl: '',
      nodeEnv: '',
      logLevel: '',
      posthogKey: '',
      posthogUrl: '',
      studioTokens: '',
      scraperUrl: '',
      devHelper: {
        enabled: true,
        features: {
          networkErrorClassifier: true,
          infiniteLoopDetector: true,
          unhandledPromiseRejectionTracker: true,
          environmentConsistencyChecker: true,
        },
      },
    },
    strapiUrl: '',
    supabaseServiceKey: '',
    googleApiKey: '',
    nasaApiKey: '',
    openaiApiKey: '',
    openaiOrg: '',
    redisFlushKey: '',
    scraperKey: '',
    razorpayKey: '',
    razorpaySecret: '',
    razorpayTestKey: '',
    razorpayTestSecret: '',
  },
})
