// Define TypeScript types from the enums
export type AccessLevel = 'viewer' | 'editor' | 'admin' | 'super_admin'
export type AddressType =
  | 'residential'
  | 'headquarters'
  | 'office'
  | 'factory'
  | 'lab'
  | 'warehouse'
  | 'research'
  | 'retail'
  | 'showroom'
  | 'branch'
export type AppPlan = 'free' | 'basic' | 'intermediate' | 'premium' | 'enterprise' | 'custom'
export type AppRole =
  | 'guest'
  | 'user'
  | 'astroguide'
  | 'mentor'
  | 'moderator'
  | 'tenant_member'
  | 'tenant_admin'
  | 'tenant_super_admin'
  | 'admin'
  | 'super_admin'
  | 'service_role'
export type ContactType = 'personal' | 'company' | 'professional' | 'recruitment' | 'founder'
export type ContentStatus =
  | 'draft'
  | 'pending_agent_action'
  | 'pending_agent_review'
  | 'pending_human_review'
  | 'pending_relevance_check'
  | 'irrelevant'
  | 'scheduled'
  | 'unpublished'
  | 'archived'
  | 'published'
  | 'failed'
  | 'pending_crawl'
  | 'scraped'
  | 'outdated'
  | 'updated'
  | 'new'
export type ContentType =
  | 'news'
  | 'events'
  | 'opportunities'
  | 'research'
  | 'companies'
  | 'contact'
  | 'people'
  | 'unknown'
export type FeedbackStatus =
  | 'new'
  | 'under_review'
  | 'backlog'
  | 'working_on'
  | 'resolved'
  | 'rejected'
  | 'deferred'
export type FeedbackType =
  | 'bug_report'
  | 'feature_request'
  | 'user_interface_issue'
  | 'performance_issue'
  | 'documentation'
export type FollowedEntity = 'company' | 'user'
export type Priority = 'very_low' | 'low' | 'medium' | 'high' | 'critical'
export type PrivacyLevel = 'private' | 'connected' | 'public'
export type ScrapeFrequency =
  | 'four_times_daily'
  | 'twice_daily'
  | 'daily'
  | 'twice_weekly'
  | 'weekly'
  | 'bi_weekly'
  | 'monthly'
  | 'quarterly'
  | 'biannual'
  | 'annually'
  | 'never'
