/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAccordion: typeof import('primevue/accordion')['default']
    PrimeAccordionContent: typeof import('primevue/accordioncontent')['default']
    PrimeAccordionHeader: typeof import('primevue/accordionheader')['default']
    PrimeAccordionPanel: typeof import('primevue/accordionpanel')['default']
    PrimeAccordionTab: typeof import('primevue/accordiontab')['default']
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCalendar: typeof import('primevue/calendar')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChart: typeof import('primevue/chart')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeForm: typeof import('@primevue/forms/form')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimePopover: typeof import('primevue/popover')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    PrimeProgressSpinner: typeof import('primevue/progressspinner')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
