# Stage 1: Build Stage
FROM node:22.14.0-bookworm AS builder

# Set environment variables for better performance and reproducibility
ENV NODE_ENV=development

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json first for better caching
COPY package.json package-lock.json ./

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN pnpm install

# Build the application using Nx
RUN pnpx nx build @astronera/website

# Stage 2: Production Stage
FROM node:22.14.0-bookworm

# Set environment variables
ENV NODE_ENV=production

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/.output ./.output

# Optionally, copy package.json and package-lock.json if runtime dependencies are needed
COPY package.json package-lock.json ./

# Install only production dependencies
RUN pnpm ci --only=production

# Expose the port Nuxt uses
EXPOSE 3000

# Start the server
CMD ["node", ".output/server/index.mjs"]
