alter table "public"."addresses" drop constraint "fk_city_id";

alter table "public"."addresses" drop constraint "fk_country_id";

alter table "public"."cities" drop constraint "fk_country_id";

drop index if exists "public"."feedback_pkey";

alter table "public"."addresses" alter column "id" drop identity;

alter table "public"."categories" alter column "id" drop identity;

alter table "public"."cities" alter column "id" drop identity;

alter table "public"."companies" alter column "id" drop identity;

alter table "public"."company_employees" drop column "id";

alter table "public"."company_news" drop column "id";

alter table "public"."contacts" alter column "id" drop identity;

alter table "public"."countries" alter column "id" drop identity;

alter table "public"."feedbacks" alter column "id" drop identity;
alter table "public"."feedbacks" alter column "id" set default nextval('public.feedback_id_seq'::regclass);


alter table "public"."news" alter column "id" drop identity;

alter table "public"."news_embeddings" alter column "id" drop identity;

alter table "public"."news_tags" alter column "id" drop identity;

alter table "public"."plan_permissions" alter column "id" set generated by default;

alter table "public"."social_media" alter column "id" drop identity;

alter table "public"."tags" alter column "id" drop identity;

alter sequence "public"."feedback_id_seq" owned by "public"."feedbacks"."id";

CREATE UNIQUE INDEX tags_name_key ON public.tags USING btree (name);

CREATE UNIQUE INDEX feedback_pkey ON public.feedbacks USING btree (id);

alter table "public"."feedbacks" add constraint "feedback_pkey" PRIMARY KEY using index "feedback_pkey";

alter table "public"."addresses" add constraint "fk_city" FOREIGN KEY (city_id) REFERENCES public.cities(id) not valid;

alter table "public"."addresses" validate constraint "fk_city";

alter table "public"."addresses" add constraint "fk_country" FOREIGN KEY (country_id) REFERENCES public.countries(id) not valid;

alter table "public"."addresses" validate constraint "fk_country";

alter table "public"."addresses" add constraint "public_addresses_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."addresses" validate constraint "public_addresses_company_id_fkey";

alter table "public"."addresses" add constraint "public_addresses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."addresses" validate constraint "public_addresses_user_id_fkey";

alter table "public"."cities" add constraint "fk_country" FOREIGN KEY (country_id) REFERENCES public.countries(id) not valid;

alter table "public"."cities" validate constraint "fk_country";

alter table "public"."companies" add constraint "fk_category" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."companies" validate constraint "fk_category";

alter table "public"."companies" add constraint "fk_social_media" FOREIGN KEY (social_media_id) REFERENCES public.social_media(id) not valid;

alter table "public"."companies" validate constraint "fk_social_media";

alter table "public"."company_employees" add constraint "company_employees_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) not valid;

alter table "public"."company_employees" validate constraint "company_employees_company_id_fkey";

alter table "public"."company_employees" add constraint "company_employees_user_profile_id_fkey" FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id) not valid;

alter table "public"."company_employees" validate constraint "company_employees_user_profile_id_fkey";

alter table "public"."company_news" add constraint "company_news_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) not valid;

alter table "public"."company_news" validate constraint "company_news_company_id_fkey";

alter table "public"."company_news" add constraint "company_news_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) not valid;

alter table "public"."company_news" validate constraint "company_news_news_id_fkey";

alter table "public"."contacts" add constraint "fk_company" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."contacts" validate constraint "fk_company";

alter table "public"."contacts" add constraint "fk_user" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE not valid;

alter table "public"."contacts" validate constraint "fk_user";

alter table "public"."feedbacks" add constraint "fk_user" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) not valid;

alter table "public"."feedbacks" validate constraint "fk_user";

alter table "public"."news" add constraint "news_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."news" validate constraint "news_category_id_fkey";

alter table "public"."news_embeddings" add constraint "news_embeddings_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."news_embeddings" validate constraint "news_embeddings_news_id_fkey";

alter table "public"."news_tags" add constraint "news_tags_news_id_fkey" FOREIGN KEY (news_id) REFERENCES public.news(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."news_tags" validate constraint "news_tags_news_id_fkey";

alter table "public"."news_tags" add constraint "news_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."news_tags" validate constraint "news_tags_tag_id_fkey";

alter table "public"."responses" add constraint "responses_id_key" UNIQUE using index "responses_id_key";

alter table "public"."responses" add constraint "responses_search_id_fkey" FOREIGN KEY (search_id) REFERENCES public.searches(id) not valid;

alter table "public"."responses" validate constraint "responses_search_id_fkey";

alter table "public"."role_permissions" add constraint "role_permission_unique" UNIQUE using index "role_permission_unique";

alter table "public"."searches" add constraint "searches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) not valid;

alter table "public"."searches" validate constraint "searches_user_id_fkey";

alter table "public"."user_profiles" add constraint "public_user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "public_user_profiles_id_fkey";

alter table "public"."user_profiles" add constraint "users_email_key" UNIQUE using index "users_email_key";


