create sequence IF NOT EXISTS "public"."categories_id_seq";

create sequence IF NOT EXISTS "public"."cities_id_seq";

create sequence IF NOT EXISTS "public"."companies_id_seq";

create sequence IF NOT EXISTS "public"."contacts_id_seq";

create sequence IF NOT EXISTS "public"."countries_id_seq";

create sequence IF NOT EXISTS "public"."news_embeddings_id_seq";

create sequence IF NOT EXISTS "public"."news_id_seq";

create sequence IF NOT EXISTS "public"."news_tags_id_seq";

create sequence IF NOT EXISTS "public"."responses_id_seq";

create sequence IF NOT EXISTS "public"."searches_id_seq";

create sequence IF NOT EXISTS "public"."social_media_id_seq";

create sequence IF NOT EXISTS "public"."tags_id_seq";

alter table "public"."company_employees" drop constraint "company_employees_pkey";

alter table "public"."company_news" drop constraint "company_news_pkey";

drop index if exists "public"."company_employees_pkey";

drop index if exists "public"."company_news_pkey";

alter table "public"."categories" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."research" alter column "id" set default extensions.gen_random_uuid();

alter table "public"."responses" alter column "id" set generated by default;

alter table "public"."role_permissions" alter column "id" set generated by default;

alter table "public"."searches" alter column "id" set generated by default;

alter table "public"."user_profiles" alter column "id" set default extensions.uuid_generate_v4();

CREATE UNIQUE INDEX company_employees_pkey ON public.company_employees USING btree (user_profile_id, company_id);

CREATE UNIQUE INDEX company_news_pkey ON public.company_news USING btree (company_id, news_id);

alter table "public"."company_employees" add constraint "company_employees_pkey" PRIMARY KEY using index "company_employees_pkey";

alter table "public"."company_news" add constraint "company_news_pkey" PRIMARY KEY using index "company_news_pkey";
